apiVersion: apps/v1
kind: Deploymant
metaData:
  name: fastapi-app
  labels:
    app: fastapi-app
spec:
  replicas: 2
  selector: 
    matchLabels: 
      app: fastapi-app
  template:
    labels:
      app: fastapi-app
    spec:
      containers:
      - name: fastapi
        image: myfastapi
        ports: 
      - containerPort: 8000
      env:
      - name: ENVIRONMENT
        value: "production"
      resources:
        requests:
          memory: "500Mi"
          cpu: "500m"
        limits:
          memory: "1000Mi"
          cpu: "1000m"
      readninessProbe:
        httpGet:
          path: /health
          port: 8000
        initialDelaySeconds: 5
        periodSeconds: 10
      livenessProbe: 
        httpGet:
          path: /health
          port: 8000
        initialDelaySeconds: 10
        periodSeconds: 15

apiVersion: v1
kind: Service
metadata:
  name: mysvc
spec:
  selector:
    app: fastapi-app
  ports:
  - protocol: TCP
    port: 80
    targetport: 8000
  type: LoadBalancer